[package]
authors = ["Sirius902"]
edition = "2024"
license = "Apache-2.0"
name = "gcviewer"
readme = "README.md"
repository = "https://github.com/Sirius902/gcviewer"
version = "0.1.0"

[build-dependencies]
git2 = { version = "0.20", default-features = false, optional = true }

[dependencies]
bincode = "1"
bytemuck = { version = "1", features = ["derive"] }
cgmath = "0.18"
clap = { version = "4", features = ["derive"] }
console-subscriber = { version = "0.5", optional = true }
directories = "6"
gcinput = { git = "https://github.com/Sirius902/gcfeeder", rev = "7794447" }
image = { version = "0.25", features = ["png"], default-features = false }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-serial = "5"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "rt"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu = "28"
winit = "0.30"

[target.'cfg(target_os = "windows")'.build-dependencies]
embed-resource = "3"
image = { version = "0.25", features = [
  "png",
  "ico",
], default-features = false }

[features]
default = ["git-version"]
git-version = ["dep:git2"]
tokio-console = ["dep:console-subscriber"]
