[package]
authors = ["Sirius902"]
edition = "2021"
license = "Apache-2.0"
name = "gcviewer"
readme = "README.md"
repository = "https://github.com/Sirius902/gcviewer"
version = "0.1.0"

[build-dependencies]
git2 = { version = "0.20", default-features = false, optional = true }

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3"
image = { version = "0.25", features = [
  "png",
  "ico",
], default-features = false }

[dependencies]
bincode = "1"
bytemuck = { version = "1", features = ["derive"] }
cgmath = "0.18"
clap = { version = "4", features = ["derive"] }
directories = "6"
enclose = "1"
gcinput = { git = "https://github.com/Sirius902/gcfeeder", tag = "v3.0.1" }
image = { version = "0.25", features = ["png"], default-features = false }
pollster = "0.4"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu = "24"
winit = "0.30"

[features]
default = ["git-version"]
git-version = ["dep:git2"]
