[package]
name = "gcviewer"
version = "3.0.0"
repository = "https://github.com/Sirius902/gcviewer/"
edition = "2021"

[dependencies]
bincode = "1.3.3"
env_logger = "0.10.0"
wgpu = "0.14.2"
winit = "0.27.5"

[dependencies.gcfeeder-core]
git = "https://github.com/Sirius902/gcfeeder"

[dependencies.log]
version = "0.4.17"
features = ["std"]

[dependencies.serde]
version = "1.0.144"
features = ["derive"]
